# Generated by Django 5.2.4 on 2025-08-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
